import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;

/** Jam Interpreter */
class Interpreter {
    
    public static void main(String[] args) {
        String p = "letrec appendz1 := map xz2,yz2,z0 to if (xz2 =null) then z0(yz2) else let z1 := first(xz2); in appendz1(rest(xz2), yz2, map z3 to z0(let z2 := z3; in cons(z1, z2))); in let sz2 := cons(1, cons(2, cons(3, null))); in appendz1(sz2, sz2, map x to x)";
        Interpreter i = new Interpreter(new StringReader(p));
        //System.out.println(i.eval());
        System.out.println(i.unshadow());
    }

    /** Abstract Syntax Tree generated by the parser */
    private AST ast;

    /** Constructor */
    Interpreter(String fileName) throws IOException { this(new Parser(fileName)); }

    /** Constructor */
    Interpreter(Reader reader) { this(new Parser(reader)); }

    /** Constructor */
    Interpreter(Parser p) { this(p.parse()); }

    /** Constructor */
    Interpreter(AST ast) { this.ast = ast; }

    /** Interprets the program using a call-by-value calling convention and a cons-by-value cons convention */
    public JamVal eval() {
        Context.check(ast);
        return this.ast.accept(
                new ASTInterpreter(
                        new Empty<Binding>(),
                        new EvaluationPolicy(EvaluationType.BY_VALUE, EvaluationType.BY_VALUE)
                        )
                );
    }
    
    public AST unshadow() {
        Context.check(ast);
        return Unshadow.convert(ast);
    }
    
    public AST convertToCPS() { return ast; }
    public JamVal cpsEval() { return JamVoid.ONLY; }
    public AST convertToSD() { return ast; }
    public JamVal SDEval() { return JamVoid.ONLY; }
    public JamVal SDCpsEval() { return JamVoid.ONLY; }
}


